#!/usr/bin/env python3
# The public keys of our addresses, from the mail repository, as the module
# the compose page imports (keys.mjs): it encrypts only to these.
import json, os
src = os.path.expanduser("~/Desktop/Projects/mail/server/openpgp")
keys = [{"address": k["address"], "fingerprint": k["fingerprint"], "armored": open(os.path.join(src, k["address"] + ".asc")).read()}
        for k in json.load(open(os.path.join(src, "keys.json")))]
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "keys.mjs"), "w") as f:
    f.write("// Generated by make-keys.py from the mail repository (server/openpgp): the keys\n"
            "// end-to-end messages written in the reader are encrypted to.\nexport const KEYS = " + json.dumps(keys, indent=1) + ";\n")
