#!/usr/bin/env python3
# The public keys of our addresses, from the mail repository, as the module
# the compose page imports (keys.mjs): it encrypts only to these. With each,
# the IDs of its encryption subkeys, so the page knows whose mark to show.
import base64, hashlib, json, os

def packets(armored):
    lines = armored.strip().splitlines()
    body = lines[lines.index("") + 1:]
    data = base64.b64decode("".join(l for l in body if not l.startswith("=") and not l.startswith("-----")))
    at = 0
    while at < len(data):
        head = data[at]; at += 1
        if head & 0x40:
            tag, first = head & 0x3F, data[at]; at += 1
            if first < 192: length = first
            elif first < 224: length = ((first - 192) << 8) + data[at] + 192; at += 1
            else: length = int.from_bytes(data[at:at + 4], "big"); at += 4
        else:
            tag, kind = (head >> 2) & 0x0F, head & 3
            n = [1, 2, 4][kind]
            length = int.from_bytes(data[at:at + n], "big"); at += n
        yield tag, data[at:at + length]
        at += length

def encryption_ids(armored):
    ids = []
    for tag, body in packets(armored):
        if tag == 14 and body[0] == 4 and body[5] == 18:  # a v4 ECDH subkey
            ids.append(hashlib.sha1(b"\x99" + len(body).to_bytes(2, "big") + body).hexdigest()[-16:])
    return ids

src = os.path.expanduser("~/Desktop/Projects/mail/server/openpgp")
keys = []
for k in json.load(open(os.path.join(src, "keys.json"))):
    armored = open(os.path.join(src, k["address"] + ".asc")).read()
    keys.append({"address": k["address"], "fingerprint": k["fingerprint"], "subkeys": encryption_ids(armored), "armored": armored})
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "keys.mjs"), "w") as f:
    f.write("// Generated by make-keys.py from the mail repository (server/openpgp): the keys\n"
            "// end-to-end messages written in the reader are encrypted to.\nexport const KEYS = " + json.dumps(keys, indent=1) + ";\n")
